name: Xamsta CI

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_xamsta_android:
    name: Build Xamsta Android
    runs-on: macos-latest

    steps:

    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Setup .NET Core SDK 5.x
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: "5.x"

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.2.0
      with:
        nuget-version: "latest"

    - name: Restore nuget packages
      run: nuget restore xamsta.sln

    - name: Build
      run: msbuild xamsta/xamsta.Android/xamsta.Android.csproj /t:PackageForAndroid /p:Configuration=Release /restore
  
  build_xamsta_ios:
    name: Build Xamsta iOS
    runs-on: macos-latest

    steps:

    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Setup .NET Core SDK 5.0.x
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '5.0.x'

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.2.0
      with:
        nuget-version: "latest"

    - name: Restore nuget packages
      run: nuget restore xamsta.sln

    - name: Build
      run: msbuild xamsta/xamsta.iOS/xamsta.iOS.csproj /p:Configuration=Debug /p:Platform=iPhoneSimulator /t:Rebuild /restore

  build_xamsta_uwp:
    name: Build Xamsta UWP
    runs-on: windows-latest

    steps:

    - name: Checkout source code
      uses: actions/checkout@v2
    
    - name: Setup .NET Core SDK 5.0.x
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '5.0.x'

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.2.0
      with:
        nuget-version: "latest"

    - name: Restore nuget packages
      run: nuget restore xamsta.sln
    
    - name: Build
      run: msbuild xamsta/xamsta.UWP/xamsta.UWP.csproj /p:Platform=x86 /p:Configuration=Debug /p:AppxPackageSigningEnabled=false /t:Rebuild /restore

  build-macos:
    name: Build Xamsta macOS
    runs-on: macos-latest

    steps:

    - name: Checkout source code
      uses: actions/checkout@v2
      
    - name: Set default Xcode 14.0.1
      run: |
        XCODE_ROOT=/Applications/Xcode_14.0.1.app
        echo "MD_APPLE_SDK_ROOT=$XCODE_ROOT" >> $GITHUB_ENV
        sudo xcode-select -s $XCODE_ROOT
        
    - name: Setup .NET Core SDK 5.0.x
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '5.0.x'
    
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.2.0
      with:
        nuget-version: "latest"

    - name: Restore nuget packages
      run: nuget restore xamsta.sln

    - name: Build
      run: msbuild xamsta/xamsta.macOS/xamsta.macOS.csproj /p:Configuration=Debug /p:CreatePackage=false /t:Rebuild /restore
