name: Xamsta CI

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_xamsta_android:
    name: Build Xamsta Android
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set default Xamarin SDK versions
        run: |
          $VM_ASSETS/select-xamarin-sdk-v2.sh --mono=6.12 --android=12.0

      - name: Setup .NET Core SDK 5.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "5.x"

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.2.0

      - name: Restore nuget packages
        run: nuget restore xamsta/xamsta.Android/xamsta.Android.csproj

      - name: Build
        run: msbuild xamsta/xamsta.Android/xamsta.Android.csproj /t:PackageForAndroid /p:Configuration=Release
